<?php

declare(strict_types=1);

namespace Noem\State\Test\Unit\Feature\Agentic\ReturnValue;

use PHPUnit\Framework\Attributes\Group;
use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;

/**
 * Acceptance Criterion: weave() result contains result key with AI-synthesized final output
 *
 * Criticality: contract
 * Intent: Provides aggregated result addressing original intent, generated by AI from tool results
 *
 * @spec /specs/features/agentic.yaml:90-93
 */
#[Group('ai'), Group('weave'), Group('return-value')]
final class ContainsFinalResultTest extends TestCase
{
    #[Test]
    public function resultContainsFinalResult(): void
    {
        $expectedStructure = [
            'selectedTools' => [],
            'toolCalls' => [],
            'result' => null,
            'iterations' => [],
            'reasoning' => '',
        ];

        $this->assertArrayHasKey('result', $expectedStructure, 'Result should contain result key');
    }
}
