name: CI

on:
    workflow_dispatch:
    push:

jobs:
    housekeeping:
        runs-on: ubuntu-latest
        steps:
            -   uses: "actions/checkout@v2"
            -   uses: "shivammathur/setup-php@v2"
                with:
                    php-version: "8.0"
            -   uses: "ramsey/composer-install@v1"
            -   name: "Sync embedded code blocks"
                run: "composer embed-files"
            -   name: "Run PHPCBF"
                run: "./vendor/bin/phpcbf > /dev/null || true"
            -   uses: "stefanzweifel/git-auto-commit-action@v4"
    test:
        needs: housekeeping
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php:
                    - "8.0"
                dependencies:
                    - "lowest"
                    - "highest"
                include:
                    -   php-version: "8.1"
                        composer-options: "--ignore-platform-reqs"

        steps:
            -   name: "Extract branch name"
                run: 'echo ::set-output name=branch::${GITHUB_REF#refs/heads/}'
                id: "extract_branch"
            -   uses: "actions/checkout@v2"
                with:
                    ref: "${{ steps.extract_branch.outputs.branch }}"
            -   uses: "shivammathur/setup-php@v2"
                with:
                    php-version: "${{ matrix.php }}"
            -   uses: "ramsey/composer-install@v1"
                with:
                    dependency-versions: "${{ matrix.dependencies }}"
                    composer-options: "${{ matrix.composer-options }}"
            -   name: "Run PHP Code Sniffer"
                run: "./vendor/bin/phpcs"
            #            -   name: Run Psalm
            #                run: ./vendor/bin/psalm
            -   name: "Run PHPUnit"
                run: "./vendor/bin/phpunit"


